# Generated by Django 4.1 on 2023-07-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Product Data',
                'verbose_name_plural': 'Product Data',
            },
        ),
    ]
