# Generated by Django 4.1 on 2023-07-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image_url',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.URLField(max_length=5000),
        ),
    ]
